#!/bin/sh
#
# RASPI-KIDZ
# Initialize and mount the storage partition
#

case "$1" in
	start)
		if [ -b /dev/mmcblk0 ] ; then
			dev=/dev/mmcblk0
			part3=/dev/mmcblk0p3
		else
			dev=/dev/vda
			part3=/dev/vda3
		fi

		if ! [ -b "${part3}" ] ; then
			printf "Creating storage partition: "
			result="OK"

			part2_end=$(partx -s -g -o END -n 2 "${dev}")
			part3_start=$((part2_end + 1))

			dev_size=$(cat "/sys/block/${dev##*/}/size")
			part3_end=$((dev_size - 1))

			if ! parted -s "${dev}" mkpart primary "${part3_start}"s "${part3_end}"s ; then
				result="FAIL"
			fi

			printf "Creating storage filesystem: "
			result="OK"
			if ! mkfs.ext4 -F -L storage "${part3}" ; then
				result="FAIL"
			fi
			echo "${result}"
		fi

		printf "Mounting storage partition: "
		mkdir -p /storage
		result="OK"
		if ! mount -o ro "${part3}" /storage ; then
			result="FAIL"
		fi
		echo "${result}"
		;;

	stop)
		printf "Unmounting storage partition: "
		result="OK"
		if ! umount /storage ; then
			result="FAIL"
		fi
		echo "${result}"
		;;
esac

exit $?
