#!/bin/sh
#
# RASPI-KIDZ
# Initialize and mount the storage partition
#

case "$1" in
	start)
		if [ -b /dev/mmcblk0 ] ; then
			dev=/dev/mmcblk0
			storage=/dev/mmcblk0p3
		else
			dev=/dev/vda
			storage=/dev/vda3
		fi

		if ! blkid | grep -q 'LABEL="storage"' ; then
			dev_size=$(cat "/sys/block/${dev##*/}/size")
			dev_end=$((dev_size - 1))

			printf "Resizing storage partition: "
			result="OK"
			if ! parted -m "${dev}" u s resizepart 3 "${dev_end}" ; then
				result="FAIL"
			fi
			echo "${result}"

			printf "Creating storage filesystem: "
			result="OK"
			if ! mkfs.ext4 -L storage "${storage}" ; then
				result="FAIL"
			fi
			echo "${result}"
		fi

		printf "Mounting storage partition: "
		mkdir -p /storage
		result="OK"
		if ! mount -o ro "${storage}" /storage ; then
			result="FAIL"
		fi
		echo "${result}"
		;;

	stop)
		printf "Unmounting storage partition: "
		result="OK"
		if ! umount /storage ; then
			result="FAIL"
		fi
		echo "${result}"
		;;
esac

exit $?
