#!/bin/sh
#
# Display splash images on poweron and shutdown
#

SPLASH_IMAGE_POWERON=/var/lib/splash/poweron.png
SPLASH_IMAGE_SHUTDOWN=/var/lib/splash/shutdown.png

case "$1" in
	start)
		printf "Displaying splash image (poweron): "
		echo "q" | /usr/bin/fbv "$SPLASH_IMAGE_POWERON" >/dev/null
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Displaying splash image (shutdown): "
		echo "q" | /usr/bin/fbv "$SPLASH_IMAGE_SHUTDOWN" >/dev/null
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit $?
