#!/bin/sh
#
# RASPI-KIDZ
# Start wpa_supplicant
#

if [ "$IFACE" = "wlan0" ] ; then
	# (Re-)start wpa_supplicant
	start-stop-daemon --stop --oknodo --exec /usr/sbin/wpa_supplicant
	start-stop-daemon --start --oknodo --name wpa_supplicant \
					  --startas /usr/sbin/wpa_supplicant \
					  -- -B -i wlan0 -c /etc/wpa_supplicant.conf
fi
