#!/bin/sh
#
# RASPI-KIDZ
# Run wpa_supplicant
#

if [ "$IFACE" = "eth0" ] ; then
	[ -e /sys/class/net/eth0 ] || exit 1
fi

if [ "$IFACE" = "wlan0" ] ; then
	[ -e /sys/class/net/wlan0 ] || exit 1

	# Run wpa_supplicant
	/usr/sbin/wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf || exit 1
fi
