#!/bin/sh
#
# RASPI-KIDZ
# Handle eth0 and wlan0 interfaces (pre-up)
#

if [ "$IFACE" = "eth0" ] ; then
	[ -e /sys/class/net/eth0 ] || exit 1
fi

if [ "$IFACE" = "wlan0" ] ; then
	grep -q "^brcmfmac " /proc/modules || exit 1

	# Wait 5 secs for /sys/class/net/wlan0 to appear
	for _ in $(seq 1 10) ; do
		if [ -e /sys/class/net/wlan0 ] ; then
			break
		fi
		sleep .5
	done
	[ -e /sys/class/net/wlan0 ] || exit 1

	# Run wpa_supplicant
	if ! [ -e /var/run/wpa_supplicant.pid ] ; then
		/usr/sbin/wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf \
								 -P /var/run/wpa_supplicant.pid || exit 1
	fi
fi
