#!/bin/sh
#
# RASPI-KIDZ
# Display a splash image on poweron
#

SPLASH_IMAGE_POWERON=/var/lib/splash/poweron.png

case "$1" in
	start)
		printf "Displaying splash image (poweron): "
		[ -e /dev/fb0 ] && dd if=/dev/zero of=/dev/fb0 >/dev/null 2>&1
		echo "q" | /usr/bin/fbv "$SPLASH_IMAGE_POWERON" >/dev/null
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	stop)
		/bin/true
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
