#!/bin/sh
#
# RASPI-KIDZ
# Start the gpiod daemon
#

case "$1" in
	start)
		printf "Starting gpiod daemon: "
		( /usr/bin/gpiod 2>&1 | logger -s -t gpiod & ) &
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	stop)
		/bin/true
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
