#!/bin/sh
#
# RASPI-KIDZ
# Restore ALSA state
#

ALSA_DEV=$(head -1 /proc/asound/cards | tr '[:upper:]' '[:lower:]')
ALSA_DEV=${ALSA_DEV#*: }
ALSA_DEV=${ALSA_DEV%% *}

case "$1" in
	start)
		printf "Restoring ALSA state for %s: " "${ALSA_DEV}"
		result="OK"
		. /etc/asound.conf."${ALSA_DEV}" || result="FAIL"
		alsactl -f /etc/asound.state."${ALSA_DEV}" restore "${DEFAULT}" || result="FAIL"
		echo "${result}"
		;;

	stop)
		/bin/true
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
