#!/bin/sh
#
# RASPI-KIDZ
# Restore ALSA state
#

case "$1" in
	start)
		for f in /proc/asound/card*/id ; do
			id=$(cat "${f}")
			if [ -e /etc/asound.state."${id}" ] ; then
				printf "Restoring ALSA state for %s: " "${id}"
				alsactl -f /etc/asound.state."${id}" restore "${id}"
				[ $? = 0 ] && echo "OK" || echo "FAIL"
			fi
		done
		;;

	stop)
		/bin/true
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
