#!/bin/sh
#
# RASPI-KIDZ
# Start/stop qplayer
#

if grep -q noqplayer /proc/cmdline ; then
	exit 0
fi

case "$1" in
	start)
		printf "Starting qplayer: "
		[ -e /dev/fb0 ] && dd if=/dev/zero of=/dev/fb0 >/dev/null 2>&1
		opts=$(cat /etc/qplayer.conf)
		( LANG=en_US.UTF-8 /usr/bin/qplayer --platform linuxfb ${opts} 2>&1 | logger -t qplayer & ) &
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	stop)
		printf "Stopping qplayer: "
		killall /usr/bin/qplayer
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
