#!/bin/sh
#
# RASPI-KIDZ
# Start/stop qplayer
#

case "$1" in
	start)
		printf "Starting qplayer: "
		( LANG=en_US.UTF-8 /usr/bin/qplayer --platform linuxfb 2>&1 | logger -t qplayer & ) &
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	stop)
		printf "Stopping qplayer: "
		killall /usr/bin/qplayer
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
