#!/bin/sh
#
# RASPI-KIDZ
# Load modules
#

case "$1" in
	start)
		printf "Loading modules: "
		grep "^[0-9a-z]" /etc/modules.conf | while read -r module ; do
			/sbin/modprobe "$module"
		done
		echo "DONE"
		;;

	stop)
		/bin/true
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
