#!/bin/sh
#
# RASPI-KIDZ
# Display a splash image on poweron
#

SPLASH_IMAGE_POWERON=/var/lib/splash/poweron.png

case "$1" in
	start)
		printf "Displaying splash image (poweron): "
		echo "q" | /usr/bin/fbv "$SPLASH_IMAGE_POWERON" >/dev/null
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
esac

exit $?
