#!/bin/sh
#
# RASPI-KIDZ
# Load modules (late)
#

STAGE=late

case "$1" in
	start)
		printf "Loading modules ($STAGE): "
		cat /etc/modules.conf | while read stage module ; do
			if [ "$stage" = "$STAGE" ] ; then
				/sbin/modprobe "$module"
			fi
		done
		echo "DONE"
		;;
	stop)
		/bin/true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit $?
